### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by rcemper** [jrpereirajr/iris-grpc-example#3]
C:\GitHub\iris-grpc-example>docker-compose build
Traceback (most recent call last):
  File "docker\api\client.py", line 268, in _raise_for_status
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\api\client.py", line 274, in _result
  File "docker\api\client.py", line 270, in _raise_for_status
  File "docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error for http+docker://localnpipe/version: Internal Server Error ("b'open \\\\
.\\pipe\\docker_engine_linux: The system cannot find the file specified.'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error for http+docker://localnp
ipe/version: Internal Server Error ("b'open \\\\.\\pipe\\docker_engine_linux: The system cannot find the file spec
ified.'")
[10736] Failed to execute script docker-compose

C:\GitHub\iris-grpc-example>

**Comment by rcemper** [comment]
update of docker desktop fixed the issue
hve no idea why
